name: Deploy Docker container to EC2

on:
  push:
    branches:
      - master  # master 브랜치에 커밋이 발생할 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/ec2-user/runeterra/
        
          git pull origin master
        
          if ! [ -x "$(command -v docker)" ]; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            sudo usermod -aG docker $USER
          fi
          
          docker stop runeterra-container || true
          docker rm runeterra-container || true
        
          docker build -t runeterra-image .
        
          docker run -d -p 80:80 --name runeterra-container runeterra-image
        EOF
